name: Annotations
description: Test printing annotations
runs:
  using: composite
  steps:
    - run: |
        npm ci
        node index.js
      shell: bash
      working-directory: ./.github/actions/annotations
