name: Playground
on:
  push:
    branches:
      - main
jobs:
  annotations:
    name: annotations
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v2
      # - uses: actions/setup-node@v2
      #   with:
      #     node-version: '14'
      #     cache: 'npm'
      # - name: print-annotation
      #   run: |
      #     echo '::info::an info message'
      #     echo '::debug::a debug message'
      #     echo '::warning::a warning message'
      #     echo '::error::an error message'
      - name: print-annotations
        uses: ./.github/actions/annotations
