name: Playground
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  annotations:
    name: playground
    runs-on: ubuntu-latest
    steps:
      # - run: |
      #     echo '::info::an info message'
      #     echo '::debug::a debug message'
      #     echo '::warning::a warning message'
      #     echo '::error::an error message'
      #     echo '::notice::a notice'
      - uses: actions/checkout@v2
      - uses: ./.github/actions/playground
        with:
          ghToken: ${{ secrets.GITHUB_TOKEN }}
